### ISSUE TITLE
`groups` command returns: not enough permissions.

### ISSUE THREAD

**Issue by itsmebirdie** [thevynk/discord-bot#3]
# Introduction

When DMing the bot with `groups` command returns to the user saying `not enough permissions`

# Steps to Reproduce

1. DM the bot with `>groups` command {variable prefix}.
2. The bot returns the error as image attached:

![image](https://user-images.githubusercontent.com/63333626/125163313-3718e380-e1aa-11eb-859b-c140f0b92218.png)

# Conclusion and Fixes

This can be fixed by restricting guild based commands in dm such as `groups` as done with moderation commands like `ban`, `kick` and `purge` i.e.,

![image](https://user-images.githubusercontent.com/63333626/125163372-77786180-e1aa-11eb-9fd9-7215a735378e.png)

restricting users to use the command in a guild channel.

**Comment by mrnightdev** [comment]
@itsmebirdie the groups command is only available to the owner(s) specified in the `config.json` file. Please add your discord id to the array of owners in `config.json` and try again.

**Comment by itsmebirdie** [comment]
Reopening issue as the topic wasn't closed.

Contents of the `config.json` file:

```json
{
  "_comment": "You can add multiple owners as an array.",
  "prefix": ">",
  "ownerID": ["706839448620498965"],
  "serverInvite": "https://discord.gg/ruZUyb8ZeS"
}
```
